#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: PostToolUse
import subprocess, sys, json, os

data = {}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project       = os.environ.get("CONTEXTWEAVE_PROJECT", "audit-project")
tool          = data.get("tool_name", "")
result_raw    = data.get("tool_response") or data.get("tool_output") or data.get("result", "")
result_preview = str(result_raw)[:500]
content       = f"Tool used: {tool}. Result: {result_preview}"

try:
    subprocess.run(
        ["contextweave", "observe", project, content,
         "--source", f"hook:PostToolUse:{tool}"],
        capture_output=True,
    )
except Exception:
    pass
