#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: PostToolFailure
import subprocess, sys, json, os

data = {}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project = os.environ.get("CONTEXTWEAVE_PROJECT", "audit-project")
tool    = data.get("tool_name", "")
error   = str(data.get("error") or data.get("tool_response", ""))[:300]

try:
    subprocess.run(
        ["contextweave", "observe", project,
         f"Tool FAILED: {tool}. Error: {error}", "--source", f"hook:PostToolFailure:{tool}"],
        capture_output=True,
    )
except Exception:
    pass
