#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: PreToolUse (observe-only, does NOT inject context)
import subprocess, sys, json, os

data = {}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project  = os.environ.get("CONTEXTWEAVE_PROJECT", "audit-project")
tool     = data.get("tool_name", "")
if tool in ("Edit", "Write", "Read", "Glob", "Grep", "Bash"):
    tool_input = str(data.get("tool_input", ""))[:300]
    try:
        subprocess.run(
            ["contextweave", "observe", project,
             f"Pre-tool: {tool}: {tool_input}", "--source", f"hook:PreToolUse:{tool}"],
            capture_output=True,
        )
    except Exception:
        pass
