#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: PreCompact
import subprocess, sys, json, os

data = {}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project = os.environ.get("CONTEXTWEAVE_PROJECT", "audit-project")
try:
    subprocess.run(
        ["contextweave", "observe", project, "Context compaction triggered",
         "--source", "hook:PreCompact"],
        capture_output=True,
    )
except Exception:
    pass
