#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: SessionStart
import subprocess, sys, json, os

data = {}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project = os.environ.get("CONTEXTWEAVE_PROJECT", "audit-project")
agent   = data.get("model", os.environ.get("CLAUDE_MODEL", "claude"))

try:
    subprocess.run(
        ["contextweave", "observe", project,
         f"Session started by {agent}", "--source", "hook:SessionStart",
         "--agent", agent],
        capture_output=True,
    )
except Exception:
    pass
