#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: SubagentStart
import subprocess, sys, json, os

data = {}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project    = os.environ.get("CONTEXTWEAVE_PROJECT", "audit-project")
agent_id   = data.get("agent_id", "unknown")
agent_type = data.get("agent_type", "")

try:
    subprocess.run(
        ["contextweave", "observe", project,
         f"Subagent started: {agent_id} ({agent_type})",
         "--source", "hook:SubagentStart"],
        capture_output=True,
    )
except Exception:
    pass
