#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: SubagentStop
import subprocess, sys, json, os

data = {}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project  = os.environ.get("CONTEXTWEAVE_PROJECT", "audit-project")
agent_id = data.get("agent_id", "unknown")

try:
    subprocess.run(
        ["contextweave", "observe", project,
         f"Subagent stopped: {agent_id}",
         "--source", "hook:SubagentStop"],
        capture_output=True,
    )
except Exception:
    pass
