"""
hooks.py — Auto-capture hooks for Claude Code, Cursor, and Gemini CLI.

Generates Python hook scripts and .claude/settings.json.
Hook event names match agentmemory's exact Claude Code hook event names
for drop-in compatibility:
  - PreToolUse
  - PostToolUse
  - SessionStart
  - Stop
  - SubagentStart
  - SubagentStop
  - PostToolFailure
  - PreCompact
"""
from __future__ import annotations

import json
import os
import stat
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Hook script templates
# ---------------------------------------------------------------------------
_SESSION_START = '''\
#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: SessionStart
import subprocess, sys, json, os

data = {{}}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project = os.environ.get("CONTEXTWEAVE_PROJECT", "{slug}")
agent   = data.get("model", os.environ.get("CLAUDE_MODEL", "claude"))

try:
    subprocess.run(
        ["contextweave", "observe", project,
         f"Session started by {{agent}}", "--source", "hook:SessionStart",
         "--agent", agent],
        capture_output=True,
    )
except Exception:
    pass
'''

_PRE_TOOL_USE = '''\
#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: PreToolUse (observe-only, does NOT inject context)
import subprocess, sys, json, os

data = {{}}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project  = os.environ.get("CONTEXTWEAVE_PROJECT", "{slug}")
tool     = data.get("tool_name", "")
if tool in ("Edit", "Write", "Read", "Glob", "Grep", "Bash"):
    tool_input = str(data.get("tool_input", ""))[:300]
    try:
        subprocess.run(
            ["contextweave", "observe", project,
             f"Pre-tool: {{tool}}: {{tool_input}}", "--source", f"hook:PreToolUse:{{tool}}"],
            capture_output=True,
        )
    except Exception:
        pass
'''

_POST_TOOL_USE = '''\
#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: PostToolUse
import subprocess, sys, json, os

data = {{}}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project       = os.environ.get("CONTEXTWEAVE_PROJECT", "{slug}")
tool          = data.get("tool_name", "")
result_raw    = data.get("tool_response") or data.get("tool_output") or data.get("result", "")
result_preview = str(result_raw)[:500]
content       = f"Tool used: {{tool}}. Result: {{result_preview}}"

try:
    subprocess.run(
        ["contextweave", "observe", project, content,
         "--source", f"hook:PostToolUse:{{tool}}"],
        capture_output=True,
    )
except Exception:
    pass
'''

_POST_TOOL_FAILURE = '''\
#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: PostToolFailure
import subprocess, sys, json, os

data = {{}}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project = os.environ.get("CONTEXTWEAVE_PROJECT", "{slug}")
tool    = data.get("tool_name", "")
error   = str(data.get("error") or data.get("tool_response", ""))[:300]

try:
    subprocess.run(
        ["contextweave", "observe", project,
         f"Tool FAILED: {{tool}}. Error: {{error}}", "--source", f"hook:PostToolFailure:{{tool}}"],
        capture_output=True,
    )
except Exception:
    pass
'''

_SUBAGENT_START = '''\
#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: SubagentStart
import subprocess, sys, json, os

data = {{}}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project    = os.environ.get("CONTEXTWEAVE_PROJECT", "{slug}")
agent_id   = data.get("agent_id", "unknown")
agent_type = data.get("agent_type", "")

try:
    subprocess.run(
        ["contextweave", "observe", project,
         f"Subagent started: {{agent_id}} ({{agent_type}})",
         "--source", "hook:SubagentStart"],
        capture_output=True,
    )
except Exception:
    pass
'''

_SUBAGENT_STOP = '''\
#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: SubagentStop
import subprocess, sys, json, os

data = {{}}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project  = os.environ.get("CONTEXTWEAVE_PROJECT", "{slug}")
agent_id = data.get("agent_id", "unknown")

try:
    subprocess.run(
        ["contextweave", "observe", project,
         f"Subagent stopped: {{agent_id}}",
         "--source", "hook:SubagentStop"],
        capture_output=True,
    )
except Exception:
    pass
'''

_STOP = '''\
#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: Stop
import subprocess, sys, json, os

data = {{}}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project = os.environ.get("CONTEXTWEAVE_PROJECT", "{slug}")
try:
    subprocess.run(["contextweave", "consolidate", project], capture_output=True)
except Exception:
    pass
try:
    subprocess.run(["contextweave", "export", project], capture_output=True)
except Exception:
    pass
'''

_SESSION_END = '''\
#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: SessionEnd  (fired when Claude Code session terminates)
import subprocess, sys, json, os

data = {{}}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project = os.environ.get("CONTEXTWEAVE_PROJECT", "{slug}")
try:
    subprocess.run(["contextweave", "consolidate", project], capture_output=True)
except Exception:
    pass
try:
    subprocess.run(["contextweave", "export", project], capture_output=True)
except Exception:
    pass
'''

_PRE_COMPACT = '''\
#!/usr/bin/env python3
# Auto-generated by contextweave — do not edit manually.
# Hook event: PreCompact
import subprocess, sys, json, os

data = {{}}
try:
    data = json.load(sys.stdin)
except Exception:
    pass

project = os.environ.get("CONTEXTWEAVE_PROJECT", "{slug}")
try:
    subprocess.run(
        ["contextweave", "observe", project, "Context compaction triggered",
         "--source", "hook:PreCompact"],
        capture_output=True,
    )
except Exception:
    pass
'''

# Map: Claude Code hook event name → (filename, template)
HOOK_DEFINITIONS = [
    ("SessionStart",    "session_start.py",       _SESSION_START),
    ("PreToolUse",      "pre_tool_use.py",         _PRE_TOOL_USE),
    ("PostToolUse",     "post_tool_use.py",        _POST_TOOL_USE),
    ("PostToolFailure", "post_tool_failure.py",    _POST_TOOL_FAILURE),
    ("SubagentStart",   "subagent_start.py",       _SUBAGENT_START),
    ("SubagentStop",    "subagent_stop.py",        _SUBAGENT_STOP),
    ("Stop",            "stop.py",                 _STOP),
    ("SessionEnd",      "session_end.py",          _SESSION_END),
    ("PreCompact",      "pre_compact.py",          _PRE_COMPACT),
]


def generate_hooks(project_slug: str, cwd: Optional[str] = None) -> list[dict]:
    """
    Write Claude Code hook scripts to .claude/hooks/ in the current directory.
    Also write .claude/settings.json registering all hooks.
    Returns list of {hook_event, file, status}.
    """
    base = Path(cwd or ".").resolve()
    hooks_dir = base / ".claude" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    results = []
    hook_entries = {}

    for event_name, filename, template in HOOK_DEFINITIONS:
        script_path = hooks_dir / filename
        content = template.format(slug=project_slug)
        script_path.write_text(content, encoding="utf-8")
        # Make executable on Unix-like systems
        try:
            current = script_path.stat().st_mode
            script_path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        except Exception:
            pass

        hook_entries[event_name] = [f"python .claude/hooks/{filename}"]
        results.append({"hook_event": event_name, "file": str(script_path), "status": "written"})

    # Write .claude/settings.json (matches agentmemory's format exactly)
    settings_path = base / ".claude" / "settings.json"
    settings = {"hooks": hook_entries}
    settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
    results.append({"hook_event": "settings", "file": str(settings_path), "status": "written"})

    return results


def generate_all_hooks(project_slug: str, cwd: Optional[str] = None) -> list[dict]:
    """
    Generate hooks for Claude Code, Cursor (.cursorrules), and Gemini CLI.
    """
    results = generate_hooks(project_slug, cwd)

    base = Path(cwd or ".").resolve()

    # Cursor — write hook instructions to .cursorrules
    cursorrules_path = base / ".cursorrules"
    cursor_block = f"""\
<!-- CW:START -->
## ContextWeave Memory Integration

This project uses contextweave for persistent memory.

**After completing any significant task, run:**
```
contextweave observe {project_slug} "description of what you did" --source cursor
```

**To retrieve relevant context before starting:**
```
contextweave search {project_slug} "your query"
```

**Environment:** Set CONTEXTWEAVE_PROJECT={project_slug}
<!-- CW:END -->
"""
    if cursorrules_path.exists():
        existing = cursorrules_path.read_text(encoding="utf-8")
        if "<!-- CW:START -->" not in existing:
            cursorrules_path.write_text(existing + "\n" + cursor_block, encoding="utf-8")
        results.append({"hook_event": "Cursor", "file": str(cursorrules_path), "status": "appended"})
    else:
        cursorrules_path.write_text(cursor_block, encoding="utf-8")
        results.append({"hook_event": "Cursor", "file": str(cursorrules_path), "status": "written"})

    # Gemini CLI — write to .gemini/ if directory exists or create it
    gemini_dir = base / ".gemini"
    gemini_dir.mkdir(exist_ok=True)
    gemini_path = gemini_dir / "system-prompt.md"
    gemini_block = f"""\
<!-- CW:START -->
## ContextWeave Memory

Project: {project_slug}
Use `contextweave observe {project_slug} "<observation>"` to save context.
Use `contextweave search {project_slug} "<query>"` to recall past context.
<!-- CW:END -->
"""
    if not gemini_path.exists():
        gemini_path.write_text(gemini_block, encoding="utf-8")
        results.append({"hook_event": "Gemini", "file": str(gemini_path), "status": "written"})

    return results
